<?php

$translations = [
    'fr' => [
        'Database Comparison Tool' => 'Outil Comparaison Base de Données',
        'Login' => 'Connexion',
        'Host' => 'Hôte',
        'Username' => 'Nom d\'utilisateur',
        'Password' => 'Mot de passe',
        "Connected as: {username}" => "Connecté en tant que : {username}",
        'Select Databases to Compare' => 'Sélectionner les bases de données à comparer',
        'Database 1' => 'Base de données 1',
        'Database 2' => 'Base de données 2',
        'Select Database 1' => 'Sélectionner la base de données 1',
        'Select Database 2' => 'Sélectionner la base de données 2',
        'Remember username' => 'Se souvenir du nom d\'utilisateur',
        'Connect' => 'Se connecter',
        "Please select two databases to compare" => "Veuillez sélectionner deux bases de données à comparer",
        'Connection failed. Please check your credentials.' => 'Échec de la connexion. Veuillez vérifier vos identifiants.',
        'Total Tables' => 'Tables totales',
        'Missing in DB1' => 'Manquante dans BD1',
        'Missing in DB2' => 'Manquante dans BD2',
        'Tables Comparison' => 'Comparaison des tables',
        'Invalid request' => 'Demande invalide',
        'Table Comparison' => 'Comparaison de la table',
        'Missing Tables in DB1' => 'Tables manquantes dans BD1',
        'Missing Tables in DB2' => 'Tables manquantes dans BD2',
        'Structure Mismatches' => 'Incompatibilités de structure',
        'Structure Mismatch' => 'Structure Incompatible',
        'Data Mismatches' => 'Incompatibilités de données',
        'Indexes DB1' => 'Indexes BD1',
        'Indexes DB2' => 'Indexes BD2',
        'No Mismatches Found' => 'Aucune incompatibilité trouvée',
        'Tables are identical' => 'Les tables sont identiques',
        'Table Structure' => 'Structure de la table',
        'Table Data' => 'Données de la table',
        'Table Name' => 'Nom de la table',
        'Column Name' => 'Nom de la colonne',
        'Column Type' => 'Type de colonne',
        'Column Length' => 'Longueur de la colonne',
        'View' => 'Voir',
        'Index' => 'Index',
        'Summary' => 'Résumé',
        'Detailed' => 'Détaillé',
        'Details' => 'Détails',
        'compare with' => 'comparer avec',
        'Identical Tables' => 'Tables identiques',
        'Identical' => 'Identique',
        'Different' => 'Différent',
        'Differences' => 'Différences',
        'Comparison Summary' => 'Résumé de la comparaison',
        'Comparison Results' => 'Résultats de la comparaison',
        'No differences found' => 'Aucune différence trouvée',
    ],
    "es"=> [
        'Database Comparison Tool' => 'Herramienta de Comparación de Bases de Datos',
        'Login' => 'Iniciar sesión',
        'Host' => 'Anfitrión',
        'Username' => 'Nombre de usuario',
        'Password' => 'Contraseña',
        "Connected as: {username}" => "Conectado como: {username}",
        'Select Databases to Compare' => 'Seleccionar Bases de Datos para Comparar',
        'Database 1' => 'Base de Datos 1',
        'Database 2' => 'Base de Datos 2',
        'Select Database 1' => 'Seleccionar Base de Datos 1',
        'Select Database 2' => 'Seleccionar Base de Datos 2',
        'Remember username' => 'Recordar nombre de usuario',
        'Connect' => 'Conectar',
        "Please select two databases to compare" => "Por favor seleccione dos bases de datos para comparar",
        'Connection failed. Please check your credentials.' => 'Conexión fallida. Por favor verifique sus credenciales.',
        'Total Tables' => 'Tablas totales',
        'Missing in DB1' => 'Faltan en BD1',
        'Missing in DB2' => 'Faltan en BD2',
        'Tables Comparison' => 'Comparación de Tablas',
        'Invalid request' => 'Solicitud inválida',
        'Table Comparison' => 'Comparación de la tabla',
        'Missing Tables in DB1' => 'Tablas faltantes en BD1',
        'Missing Tables in DB2' => 'Tablas faltantes en BD2',
        'Structure Mismatches' => 'Incompatibilidades de estructura',
        'Structure Mismatch' => 'Estructura Incompatible',
        'Data Mismatches' => 'Incompatibilidades de datos',
        'Indexes DB1' => 'Índices BD1',
        'Indexes DB2' => 'Índices BD2',
        'No Mismatches Found' => 'No se encontraron incompatibilidades',
        'Tables are identical' => 'Las tablas son idénticas',
        'Table Structure' => 'Estructura de la tabla',
        'Table Data' => 'Datos de la tabla',
        'Table Name' => 'Nombre de la tabla',
        'Column Name' => 'Nombre de la columna',
        'Column Type' => 'Tipo de columna',
        'Column Length' => 'Longitud de la columna',
        'View' => 'Ver',
        'Index' => 'Índice',
        'Summary' => 'Resumen',
        'Detailed' => 'Detallado',
        'Details' => 'Detalles',
        'compare with' => 'comparar con',
        'Identical Tables' => 'Tablas idénticas',
        'Identical' => 'Idéntico',
        'Different' => 'Diferente',
        'Differences' => 'Diferencias',
        'Comparison Summary' => 'Resumen de la comparación',
        'Comparison Results' => 'Resultados de la comparación',
        'No differences found' => 'No se encontraron diferencias',
    ],
    "de" => [
        'Database Comparison Tool' => 'Werkzeug zum Datenbankvergleich',
        'Login' => 'Anmelden',
        'Host' => 'Host',
        'Username' => 'Benutzername',
        'Password' => 'Passwort',
        "Connected as: {username}" => "Angemeldet als: {username}",
        'Select Databases to Compare' => 'Datenbanken zum Vergleichen auswählen',
        'Database 1' => 'Datenbank 1',
        'Database 2' => 'Datenbank 2',
        'Select Database 1' => 'Datenbank 1 auswählen',
        'Select Database 2' => 'Datenbank 2 auswählen',
        'Remember username' => 'Benutzername merken',
        'Connect' => 'Verbinden',
        "Please select two databases to compare" => "Bitte wählen Sie zwei Datenbanken zum Vergleichen aus",
        'Connection failed. Please check your credentials.' => 'Verbindung fehlgeschlagen. Bitte überprüfen Sie Ihre Zugangsdaten.',
        'Total Tables' => 'Gesamte Tabellen',
        'Missing in DB1' => 'Fehlt in DB1',
        'Missing in DB2' => 'Fehlt in DB2',
        'Tables Comparison' => 'Tabellenvergleich',
        'Invalid request' => 'Ungültige Anfrage',
        'Table Comparison' => 'Tabellenvergleich',
        'Missing Tables in DB1' => 'Fehlende Tabellen in DB1',
        'Missing Tables in DB2' => 'Fehlende Tabellen in DB2',
        'Structure Mismatches' => 'Strukturunterschiede',
        'Structure Mismatch' => 'Strukturfehler',
        'Data Mismatches' => 'Datenunterschiede',
        'Indexes DB1' => 'Indizes DB1',
        'Indexes DB2' => 'Indizes DB2',
        'No Mismatches Found' => 'Keine Abweichungen gefunden',
        'Tables are identical' => 'Die Tabellen sind identisch',
        'Table Structure' => 'Tabellenstruktur',
        'Table Data' => 'Tabellendaten',
        'Table Name' => 'Tabellenname',
        'Column Name' => 'Spaltenname',
        'Column Type' => 'Spaltentyp',
        'Column Length' => 'Spaltenlänge',
        'View' => 'Ansicht',
        'Index' => 'Index',
        'Summary' => 'Zusammenfassung',
        'Detailed' => 'Detailliert',
        'Details' => 'Details',
        'compare with' => 'vergleichen mit',
        'Identical Tables' => 'Identische Tabellen',
        'Identical' => 'Identisch',
        'Different' => 'Unterschiedlich',
        'Differences' => 'Unterschiede',
        'Comparison Summary' => 'Vergleichszusammenfassung',
        'Comparison Results' => 'Vergleichsergebnisse',
        'No differences found' => 'Keine Unterschiede gefunden',
    ],
    "pt" => [
        'Database Comparison Tool' => 'Ferramenta de Comparação de Bancos de Dados',
        'Login' => 'Entrar',
        'Host' => 'Host',
        'Username' => 'Nome de usuário',
        'Password' => 'Senha',
        "Connected as: {username}" => "Conectado como: {username}",
        'Select Databases to Compare' => 'Selecionar Bancos de Dados para Comparar',
        'Database 1' => 'Banco de Dados 1',
        'Database 2' => 'Banco de Dados 2',
        'Select Database 1' => 'Selecionar Banco de Dados 1',
        'Select Database 2' => 'Selecionar Banco de Dados 2',
        'Remember username' => 'Lembrar nome de usuário',
        'Connect' => 'Conectar',
        "Please select two databases to compare" => "Por favor selecione dois bancos de dados para comparar",
        'Connection failed. Please check your credentials.' => 'Falha de conexão. Por favor verifique suas credenciais.',
        'Total Tables' => 'Tabelas totais',
        'Missing in DB1' => 'Faltando em BD1',
        'Missing in DB2' => 'Faltando em BD2',
        'Tables Comparison' => 'Comparação de Tabelas',
        'Invalid request' => 'Requisição inválida',
        'Table Comparison' => 'Comparação de Tabela',
        'Missing Tables in DB1' => 'Tabelas faltando em BD1',
        'Missing Tables in DB2' => 'Tabelas faltando em BD2',
        'Structure Mismatches' => 'Incompatibilidades de estrutura',
        'Structure Mismatch' => 'Estrutura incompatível',
        'Data Mismatches' => 'Incompatibilidades de dados',
        'Indexes DB1' => 'Índices BD1',
        'Indexes DB2' => 'Índices BD2',
        'No Mismatches Found' => 'Nenhuma incompatibilidade encontrada',
        'Tables are identical' => 'As tabelas são idênticas',
        'Table Structure' => 'Estrutura da Tabela',
        'Table Data' => 'Dados da Tabela',
        'Table Name' => 'Nome da Tabela',
        'Column Name' => 'Nome da Coluna',
        'Column Type' => 'Tipo da Coluna',
        'Column Length' => 'Tamanho da Coluna',
        'View' => 'Ver',
        'Index' => 'Índice',
        'Summary' => 'Resumo',
        'Detailed' => 'Detalhado',
        'Details' => 'Detalhes',
        'compare with' => 'comparar com',
        'Identical Tables' => 'Tabelas idênticas',
        'Identical' => 'Idênticas',
        'Different' => 'Diferentes',
        'Differences' => 'Diferenças',
        'Comparison Summary' => 'Resumo da Comparação',
        'Comparison Results' => 'Resultados da Comparação',
        'No differences found' => 'Nenhuma diferença encontrada',
    ],
];

//$defaultLang = 'es';
if (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
    $detectedLang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
    if (isset($translations[$detectedLang])) {
        $defaultLang = $detectedLang;
    }
}

function T($key, $vars=[], $lang = null) {
    global $translations, $defaultLang;
    if ($lang === null) {
        $lang = $defaultLang;
    }

    if (isset($translations[$lang][$key])) {
        $retval = $translations[$lang][$key];
    } else {
        $retval = $key; // Return the key if translation is not found
    }

    
    foreach ($vars as $var => $value) {
        $retval = str_replace('{' . $var . '}', $value, $retval);
    }

    return $retval;
}

